# Generated by Django 4.0.2 on 2022-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.CharField(max_length=20)),
                ('comment', models.TextField(null=True)),
                ('review', models.TextField(null=True)),
                ('date', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.EmailField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
