# Generated by Django 4.0.2 on 2022-02-18 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APINicaMovies', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 19, 47, 36, 33104)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
