# Generated by Django 4.0.2 on 2022-02-19 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APINicaMovies', '0003_film_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 17, 50, 45, 190377)),
        ),
        migrations.AlterField(
            model_name='film',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
